version: "3"
services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/go/src/app
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: go_app_dev
      MYSQL_HOST: dockerMySQL
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
  db:
    image: mysql:5.7
    container_name: dockerMySQL
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: go_app_dev
      MYSQL_USER: docker
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    volumes:
      - ./database:/docker-entrypoint-initdb.d